[build]
  command = "npm run build"
  publish = ".next"


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "https://cdn.sanity.io/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Keep Sharp for image optimization
  NEXT_SHARP_PATH = "./node_modules/sharp"
  # Add Node.js version for consistency
  NODE_VERSION = "18"